export const Kilograms = [
    { id: '10' },
    { id: '11' },
    { id: '12' },
    { id: '13' },
    { id: '14' },
    { id: '15' },
    { id: '16' },
    { id: '17' },
    { id: '18' },
    { id: '19' },
    { id: '20' },
    { id: '21' },
    { id: '22' },
    { id: '23' },
    { id: '24' },
    { id: '25' },
    { id: '26' },
    { id: '27' },
    { id: '28' },
    { id: '29' },
    { id: '30' },
    { id: '31' },
    { id: '32' },
    { id: '33' },
    { id: '34' },
    { id: '35' },
    { id: '36' },
    { id: '37' },
    { id: '38' },
    { id: '39' },
    { id: '40' },
    { id: '41' },
    { id: '42' },
    { id: '43' },
    { id: '44' },
    { id: '45' },
    { id: '46' },
    { id: '47' },
    { id: '48' },
    { id: '49' },
    { id: '50' },
    { id: '51' },
    { id: '52' },
    { id: '53' },
    { id: '54' },
    { id: '55' },
    { id: '56' },
    { id: '57' },
    { id: '58' },
    { id: '59' },
    { id: '60' },
]
export const Centimeter = [
    { id: '100' },
    { id: '101' },
    { id: '102' },
    { id: '103' },
    { id: '104' },
    { id: '105' },
    { id: '106' },
    { id: '107' },
    { id: '108' },
    { id: '109' },
    { id: '110' },
    { id: '111' },
    { id: '112' },
    { id: '113' },
    { id: '114' },
    { id: '115' },
    { id: '116' },
    { id: '117' },
    { id: '118' },
    { id: '119' },
    { id: '120' },
    { id: '121' },
    { id: '122' },
    { id: '123' },
    { id: '124' },
    { id: '125' },
    { id: '126' },
    { id: '127' },
    { id: '128' },
    { id: '129' },
    { id: '130' },
    { id: '131' },
    { id: '132' },
    { id: '133' },
    { id: '134' },
    { id: '135' },
    { id: '136' },
    { id: '137' },
    { id: '138' },
    { id: '139' },
    { id: '140' },
    { id: '141' },
    { id: '142' },
    { id: '143' },
    { id: '144' },
    { id: '145' },
    { id: '146' },
    { id: '147' },
    { id: '148' },
    { id: '149' },
    { id: '150' },
]
export const feet = [
    { id: '1' },
    { id: '2' },
    { id: '3' },
    { id: '4' },
    { id: '5' },
    { id: '6' },
    { id: '7' },
    { id: '8' },
    { id: '9' },
    { id: '10' },
    { id: '12' },
]
export const Question = [
    {
        id: 0,
        start: 'Hi lets start with creating your profile detail',
        message: 'What is your name?',
    },
    {
        id: 1,
        message: 'What is your age?',
        name: "Select age",
    },
    {
        id: 2,
        message: 'What is your gender?',
        select1: 'Male',
        select2: 'Female'
    },
    {
        id: 3,
        message: 'Great start! Just few more questions',
    },
    {
        id: 4,
        message: 'What is your height?',
        select1: 'feet.inch',
        select2: 'cms',
    },
    {
        id: 5,
        message: 'What is your last measured weight?',
        select1: 'Kilograms',
        select2: 'Pounds',
    },
    {
        id: 6,
        message: 'Pick your nearest daily routine',
        preferece: [
            { id: 1, food: 'Sedentary (little /no exercise & desk job)' },
            { id: 2, food: 'Lightly Active (light exercise 1-3 days / wk)' },
            { id: 3, food: 'Moderately Active (moderate exercise 3-5 days / wk)' },
            { id: 4, food: 'Very Active (heavy exercise 6-7 days / week) ' },
            { id: 5, food: 'Extremely Active (very heavy exercise, hard labour job, training 2x / day)' },
        ]

    },
    {
        id: 7,
        message: 'What is your life style status?',
        preferece: [
            { id: 1, food: 'Working' },
            { id: 2, food: 'Student' },
            { id: 3, food: 'Retired' },
            { id: 4, food: 'House-wife' },
            { id: 5, food: 'Sabbatical' },
        ]

    },
    {
        id: 8,
        message: 'Name any known food allergy?',
        select1: "None"
    },
    {
        id: 9,
        message: 'Choose your food preferences?',
        preferece: [
            { id: 1, food: "Vegeterian" },
            { id: 2, food: 'Veg with Eggs' },
            { id: 3, food: 'Non-Veg' }
        ],
        data: [
            { id: 1, data: 'Monday' },
            { id: 2, data: 'Tuesday' },
            { id: 3, data: 'Wednesday' },
            { id: 4, data: 'Thrusday' },
            { id: 5, data: 'Friday' },
            { id: 5, data: 'Saturday' },
            { id: 5, data: 'Sunday' },
        ]
    },
    {
        id: 10,
        message: 'Choose your fasting days?',
        preferece: [
            { id: 1, food: "None" },
            { id: 2, food: 'Pick your days' }
        ],
        data: [
            { id: 1, data: 'Monday' },
            { id: 2, data: 'Tuesday' },
            { id: 3, data: 'Wednesday' },
            { id: 4, data: 'Thrusday' },
            { id: 5, data: 'Friday' },
            { id: 5, data: 'Saturday' },
            { id: 5, data: 'Sunday' },
        ]
    },
    {
        id: 11,
        message: 'What is your Email id?',
        select1: 'Submit'
    }

]